#ifndef GPU_WRAPPER_MODULE_CONFIG_H_
#define GPU_WRAPPER_MODULE_CONFIG_H_

#define GPU_API_OPENGL 460
//#define GPU_API_VULKAN
//#define GPU_API_DIRECTX11
//#define GPU_API_DIRECTX12

#endif//GPU_WRAPPER_MODULE_CONFIG_H_