
#ifndef _AFTER_TYPES_MOVEMENT_ENUM_H_
#define _AFTER_TYPES_MOVEMENT_ENUM_H_

#include "core/types/types.h"

namespace NPC
{
	enum eMovementEnumeration : int16_t
	{
		MOVEMENT_DEFAULT=0,

		MOVEMENT_ONGROUND=0,
		MOVEMENT_FALLING,
		MOVEMENT_WATER,
		MOVEMENT_SLIDING,

		MOVEMENT_PARKOUR_SLIDE,

		MOVEMENT_STUN_LIGHT,
		MOVEMENT_STUN_HEAVY,
		MOVEMENT_STUN_GENERAL,

		MOVEMENT_MINIDASH,

		MOVEMENT_STUN_FALL_BACKWARDS,

		MOVEMENT_SAVIORIZE,
		MOVEMENT_DEAD,
		MOVEMENT_DEAD_RECOVER,

		MOVEMENT_ATK_GROUND,
		MOVEMENT_ATK_AIR,
		MOVEMENT_ATK_SLIDE,

		MOVEMENT_UNKNOWN = -1
	};

	enum eCameratypeEnumeration : int16_t
	{
		CAMERA_MATCH = -1,
		CAMERA_DEFAULT = 0,
		CAMERA_THIRDPERSON = 1,
		CAMERA_OVERVIEW = 2,
		CAMERA_CINIMEATIC_THIRDPERSON = 3,
		CAMERA_MONTAGE = 4,
		CAMERA_STUDIOSHAFT = 5,

		CAMERA_SETTING_ANIMLOCK_OFF = 254,
		CAMERA_SETTING_ANIMLOCK_ON = 255
	};
}

#endif//_AFTER_TYPES_MOVEMENT_ENUM_H_