/*
 *
 * Confidential Information of Telekinesys Research Limited (t/a Havok). Not for disclosure or distribution without Havok's
 * prior written consent. This software contains code, techniques and know-how which is confidential and proprietary to Havok.
 * Level 2 and Level 3 source code contains trade secrets of Havok. Havok Software (C) Copyright 1999-2012 Telekinesys Research Limited t/a Havok. All Rights Reserved. Use of this software is subject to the terms of an end user license agreement.
 *
 */

//HK_REFLECTION_PARSER_EXCLUDE_FILE

// Autogenerated by generateReflections.py (projectClassList.py)
// Changes will not be lost unless:
// - The workspace is re-generated using build.py
// - The corresponding reflection database (reflection.db) is deleted
// - The --force-output or --force-rebuild option is added to the pre-build generateReflection.py execution

#include "Reflections/hkpVehicleWheelCollideReflection.cpp"
#include "Reflections/hkpTyremarksInfoReflection.cpp"
#include "Reflections/hkpVehicleDefaultSteeringReflection.cpp"
#include "Reflections/hkpVehicleDefaultVelocityDamperReflection.cpp"
#include "Reflections/hkpVehicleCastBatchingManagerReflection.cpp"
#include "Reflections/hkpVehicleDefaultSuspensionReflection.cpp"
#include "Reflections/hkpVehicleLinearCastBatchingManagerReflection.cpp"
#include "Reflections/hkpVehicleDefaultTransmissionReflection.cpp"
#include "Reflections/hkpVehicleDefaultEngineReflection.cpp"
#include "Reflections/hkpVehicleInstanceReflection.cpp"
#include "Reflections/hkpVehicleDriverInputReflection.cpp"
#include "Reflections/hkpVehicleDefaultAnalogDriverInputReflection.cpp"
#include "Reflections/hkpMultithreadedVehicleManagerReflection.cpp"
#include "Reflections/hkpVehicleAerodynamicsReflection.cpp"
#include "Reflections/hkpVehicleRayCastBatchingManagerReflection.cpp"
#include "Reflections/hkpVehicleSteeringReflection.cpp"
#include "Reflections/hkpVehicleVelocityDamperReflection.cpp"
#include "Reflections/hkpVehicleManagerReflection.cpp"
#include "Reflections/hkpVehicleDefaultAerodynamicsReflection.cpp"
#include "Reflections/hkpVehicleRayCastWheelCollideReflection.cpp"
#include "Reflections/hkpVehicleSuspensionReflection.cpp"
#include "Reflections/hkpVehicleFrictionReflection.cpp"
#include "Reflections/hkpVehicleLinearCastWheelCollideReflection.cpp"
#include "Reflections/hkpVehicleEngineReflection.cpp"
#include "Reflections/hkpVehicleDefaultBrakeReflection.cpp"
#include "Reflections/hkpVehicleDataReflection.cpp"
#include "Reflections/hkpVehicleTransmissionReflection.cpp"
#include "Reflections/hkpRejectChassisListenerReflection.cpp"
#include "Reflections/hkpVehicleBrakeReflection.cpp"

/*
 * Havok SDK - NO SOURCE PC DOWNLOAD, BUILD(#20120119)
 * 
 * Confidential Information of Havok.  (C) Copyright 1999-2012
 * Telekinesys Research Limited t/a Havok. All Rights Reserved. The Havok
 * Logo, and the Havok buzzsaw logo are trademarks of Havok.  Title, ownership
 * rights, and intellectual property rights in the Havok software remain in
 * Havok and/or its suppliers.
 * 
 * Use of this software for evaluation purposes is subject to and indicates
 * acceptance of the End User licence Agreement for this product. A copy of
 * the license is included with this software and is also available at www.havok.com/tryhavok.
 * 
 */
