#pragma once
#include "renderer/material/ShaderVariations.h"

RR_SHADER_VARIANT_BEGIN(shade_lighting_p)
	SHADER_BOOL(VARIANT_DEBUG_GBUFFERS)
	//SHADER_BOOL(VARIANT_DEBUG_SURFACE)
	SHADER_BOOL(VARIANT_DEBUG_LIGHTING)
	
	SHADER_BOOL(VARIANT_PASS_DO_INDIRECT_EMISSIVE)
	SHADER_BOOL(VARIANT_PASS_DO_DIRECT_DIRECTIONAL)
	SHADER_BOOL(VARIANT_PASS_DO_DIRECT_OMNI)
	SHADER_BOOL(VARIANT_PASS_DO_DIRECT_SPOTLIGHT)
	// for testing
	//SHADER_ENUM<0,1,2> VARIANT_DEBUG_SELECTION;

	RR_SHADER_VARIANT_COLLECT_BEGIN(shade_lighting_p)
		RR_SHADER_COLLECT(VARIANT_DEBUG_GBUFFERS)
		//RR_SHADER_COLLECT(VARIANT_DEBUG_SURFACE)
		RR_SHADER_COLLECT(VARIANT_DEBUG_LIGHTING)
		
		RR_SHADER_COLLECT(VARIANT_PASS_DO_INDIRECT_EMISSIVE)
		RR_SHADER_COLLECT(VARIANT_PASS_DO_DIRECT_DIRECTIONAL)
		RR_SHADER_COLLECT(VARIANT_PASS_DO_DIRECT_OMNI)
		RR_SHADER_COLLECT(VARIANT_PASS_DO_DIRECT_SPOTLIGHT)
	RR_SHADER_VARIANT_COLLECT_END()
RR_SHADER_VARIANT_END();