//===============================================================================================//
//
//      1Engine autogenerated source.
//
// Please be gentle. Generated from wgl.h
//
//===============================================================================================//
#ifdef _WIN32
#include "wgl_impl.h"
#include "core/os.h"
#ifdef __cplusplus
extern "C" {
#endif /*__cplusplus*/
PFNWGLCREATEBUFFERREGIONARBPROC wglCreateBufferRegionARB = NULL;
PFNWGLDELETEBUFFERREGIONARBPROC wglDeleteBufferRegionARB = NULL;
PFNWGLSAVEBUFFERREGIONARBPROC wglSaveBufferRegionARB = NULL;
PFNWGLRESTOREBUFFERREGIONARBPROC wglRestoreBufferRegionARB = NULL;
PFNWGLCREATECONTEXTATTRIBSARBPROC wglCreateContextAttribsARB = NULL;
PFNWGLMAKECONTEXTCURRENTARBPROC wglMakeContextCurrentARB = NULL;
PFNWGLGETCURRENTREADDCARBPROC wglGetCurrentReadDCARB = NULL;
PFNWGLCREATEPBUFFERARBPROC wglCreatePbufferARB = NULL;
PFNWGLGETPBUFFERDCARBPROC wglGetPbufferDCARB = NULL;
PFNWGLRELEASEPBUFFERDCARBPROC wglReleasePbufferDCARB = NULL;
PFNWGLDESTROYPBUFFERARBPROC wglDestroyPbufferARB = NULL;
PFNWGLQUERYPBUFFERARBPROC wglQueryPbufferARB = NULL;
PFNWGLGETPIXELFORMATATTRIBIVARBPROC wglGetPixelFormatAttribivARB = NULL;
PFNWGLGETPIXELFORMATATTRIBFVARBPROC wglGetPixelFormatAttribfvARB = NULL;
PFNWGLCHOOSEPIXELFORMATARBPROC wglChoosePixelFormatARB = NULL;
PFNWGLBINDTEXIMAGEARBPROC wglBindTexImageARB = NULL;
PFNWGLRELEASETEXIMAGEARBPROC wglReleaseTexImageARB = NULL;
PFNWGLSETPBUFFERATTRIBARBPROC wglSetPbufferAttribARB = NULL;
PFNWGLSETSTEREOEMITTERSTATE3DLPROC wglSetStereoEmitterState3DL = NULL;
PFNWGLGETGPUIDSAMDPROC wglGetGPUIDsAMD = NULL;
PFNWGLGETGPUINFOAMDPROC wglGetGPUInfoAMD = NULL;
PFNWGLGETCONTEXTGPUIDAMDPROC wglGetContextGPUIDAMD = NULL;
PFNWGLCREATEASSOCIATEDCONTEXTAMDPROC wglCreateAssociatedContextAMD = NULL;
PFNWGLCREATEASSOCIATEDCONTEXTATTRIBSAMDPROC wglCreateAssociatedContextAttribsAMD = NULL;
PFNWGLDELETEASSOCIATEDCONTEXTAMDPROC wglDeleteAssociatedContextAMD = NULL;
PFNWGLMAKEASSOCIATEDCONTEXTCURRENTAMDPROC wglMakeAssociatedContextCurrentAMD = NULL;
PFNWGLGETCURRENTASSOCIATEDCONTEXTAMDPROC wglGetCurrentAssociatedContextAMD = NULL;
PFNWGLBLITCONTEXTFRAMEBUFFERAMDPROC wglBlitContextFramebufferAMD = NULL;
PFNWGLCREATEDISPLAYCOLORTABLEEXTPROC wglCreateDisplayColorTableEXT = NULL;
PFNWGLLOADDISPLAYCOLORTABLEEXTPROC wglLoadDisplayColorTableEXT = NULL;
PFNWGLBINDDISPLAYCOLORTABLEEXTPROC wglBindDisplayColorTableEXT = NULL;
PFNWGLDESTROYDISPLAYCOLORTABLEEXTPROC wglDestroyDisplayColorTableEXT = NULL;
PFNWGLMAKECONTEXTCURRENTEXTPROC wglMakeContextCurrentEXT = NULL;
PFNWGLGETCURRENTREADDCEXTPROC wglGetCurrentReadDCEXT = NULL;
PFNWGLCREATEPBUFFEREXTPROC wglCreatePbufferEXT = NULL;
PFNWGLGETPBUFFERDCEXTPROC wglGetPbufferDCEXT = NULL;
PFNWGLRELEASEPBUFFERDCEXTPROC wglReleasePbufferDCEXT = NULL;
PFNWGLDESTROYPBUFFEREXTPROC wglDestroyPbufferEXT = NULL;
PFNWGLQUERYPBUFFEREXTPROC wglQueryPbufferEXT = NULL;
PFNWGLGETPIXELFORMATATTRIBIVEXTPROC wglGetPixelFormatAttribivEXT = NULL;
PFNWGLGETPIXELFORMATATTRIBFVEXTPROC wglGetPixelFormatAttribfvEXT = NULL;
PFNWGLCHOOSEPIXELFORMATEXTPROC wglChoosePixelFormatEXT = NULL;
PFNWGLSWAPINTERVALEXTPROC wglSwapIntervalEXT = NULL;
PFNWGLGETSWAPINTERVALEXTPROC wglGetSwapIntervalEXT = NULL;
PFNWGLGETDIGITALVIDEOPARAMETERSI3DPROC wglGetDigitalVideoParametersI3D = NULL;
PFNWGLSETDIGITALVIDEOPARAMETERSI3DPROC wglSetDigitalVideoParametersI3D = NULL;
PFNWGLGETGAMMATABLEPARAMETERSI3DPROC wglGetGammaTableParametersI3D = NULL;
PFNWGLSETGAMMATABLEPARAMETERSI3DPROC wglSetGammaTableParametersI3D = NULL;
PFNWGLGETGAMMATABLEI3DPROC wglGetGammaTableI3D = NULL;
PFNWGLSETGAMMATABLEI3DPROC wglSetGammaTableI3D = NULL;
PFNWGLENABLEGENLOCKI3DPROC wglEnableGenlockI3D = NULL;
PFNWGLDISABLEGENLOCKI3DPROC wglDisableGenlockI3D = NULL;
PFNWGLISENABLEDGENLOCKI3DPROC wglIsEnabledGenlockI3D = NULL;
PFNWGLGENLOCKSOURCEI3DPROC wglGenlockSourceI3D = NULL;
PFNWGLGETGENLOCKSOURCEI3DPROC wglGetGenlockSourceI3D = NULL;
PFNWGLGENLOCKSOURCEEDGEI3DPROC wglGenlockSourceEdgeI3D = NULL;
PFNWGLGETGENLOCKSOURCEEDGEI3DPROC wglGetGenlockSourceEdgeI3D = NULL;
PFNWGLGENLOCKSAMPLERATEI3DPROC wglGenlockSampleRateI3D = NULL;
PFNWGLGETGENLOCKSAMPLERATEI3DPROC wglGetGenlockSampleRateI3D = NULL;
PFNWGLGENLOCKSOURCEDELAYI3DPROC wglGenlockSourceDelayI3D = NULL;
PFNWGLGETGENLOCKSOURCEDELAYI3DPROC wglGetGenlockSourceDelayI3D = NULL;
PFNWGLQUERYGENLOCKMAXSOURCEDELAYI3DPROC wglQueryGenlockMaxSourceDelayI3D = NULL;
PFNWGLCREATEIMAGEBUFFERI3DPROC wglCreateImageBufferI3D = NULL;
PFNWGLDESTROYIMAGEBUFFERI3DPROC wglDestroyImageBufferI3D = NULL;
PFNWGLASSOCIATEIMAGEBUFFEREVENTSI3DPROC wglAssociateImageBufferEventsI3D = NULL;
PFNWGLRELEASEIMAGEBUFFEREVENTSI3DPROC wglReleaseImageBufferEventsI3D = NULL;
PFNWGLENABLEFRAMELOCKI3DPROC wglEnableFrameLockI3D = NULL;
PFNWGLDISABLEFRAMELOCKI3DPROC wglDisableFrameLockI3D = NULL;
PFNWGLISENABLEDFRAMELOCKI3DPROC wglIsEnabledFrameLockI3D = NULL;
PFNWGLQUERYFRAMELOCKMASTERI3DPROC wglQueryFrameLockMasterI3D = NULL;
PFNWGLGETFRAMEUSAGEI3DPROC wglGetFrameUsageI3D = NULL;
PFNWGLBEGINFRAMETRACKINGI3DPROC wglBeginFrameTrackingI3D = NULL;
PFNWGLENDFRAMETRACKINGI3DPROC wglEndFrameTrackingI3D = NULL;
PFNWGLQUERYFRAMETRACKINGI3DPROC wglQueryFrameTrackingI3D = NULL;
PFNWGLDXSETRESOURCESHAREHANDLENVPROC wglDXSetResourceShareHandleNV = NULL;
PFNWGLDXOPENDEVICENVPROC wglDXOpenDeviceNV = NULL;
PFNWGLDXCLOSEDEVICENVPROC wglDXCloseDeviceNV = NULL;
PFNWGLDXREGISTEROBJECTNVPROC wglDXRegisterObjectNV = NULL;
PFNWGLDXUNREGISTEROBJECTNVPROC wglDXUnregisterObjectNV = NULL;
PFNWGLDXOBJECTACCESSNVPROC wglDXObjectAccessNV = NULL;
PFNWGLDXLOCKOBJECTSNVPROC wglDXLockObjectsNV = NULL;
PFNWGLDXUNLOCKOBJECTSNVPROC wglDXUnlockObjectsNV = NULL;
PFNWGLCOPYIMAGESUBDATANVPROC wglCopyImageSubDataNV = NULL;
PFNWGLDELAYBEFORESWAPNVPROC wglDelayBeforeSwapNV = NULL;
PFNWGLENUMGPUSNVPROC wglEnumGpusNV = NULL;
PFNWGLENUMGPUDEVICESNVPROC wglEnumGpuDevicesNV = NULL;
PFNWGLCREATEAFFINITYDCNVPROC wglCreateAffinityDCNV = NULL;
PFNWGLENUMGPUSFROMAFFINITYDCNVPROC wglEnumGpusFromAffinityDCNV = NULL;
PFNWGLDELETEDCNVPROC wglDeleteDCNV = NULL;
PFNWGLENUMERATEVIDEODEVICESNVPROC wglEnumerateVideoDevicesNV = NULL;
PFNWGLBINDVIDEODEVICENVPROC wglBindVideoDeviceNV = NULL;
PFNWGLQUERYCURRENTCONTEXTNVPROC wglQueryCurrentContextNV = NULL;
PFNWGLJOINSWAPGROUPNVPROC wglJoinSwapGroupNV = NULL;
PFNWGLBINDSWAPBARRIERNVPROC wglBindSwapBarrierNV = NULL;
PFNWGLQUERYSWAPGROUPNVPROC wglQuerySwapGroupNV = NULL;
PFNWGLQUERYMAXSWAPGROUPSNVPROC wglQueryMaxSwapGroupsNV = NULL;
PFNWGLQUERYFRAMECOUNTNVPROC wglQueryFrameCountNV = NULL;
PFNWGLRESETFRAMECOUNTNVPROC wglResetFrameCountNV = NULL;
PFNWGLFREEMEMORYNVPROC wglFreeMemoryNV = NULL;
PFNWGLBINDVIDEOCAPTUREDEVICENVPROC wglBindVideoCaptureDeviceNV = NULL;
PFNWGLENUMERATEVIDEOCAPTUREDEVICESNVPROC wglEnumerateVideoCaptureDevicesNV = NULL;
PFNWGLLOCKVIDEOCAPTUREDEVICENVPROC wglLockVideoCaptureDeviceNV = NULL;
PFNWGLQUERYVIDEOCAPTUREDEVICENVPROC wglQueryVideoCaptureDeviceNV = NULL;
PFNWGLRELEASEVIDEOCAPTUREDEVICENVPROC wglReleaseVideoCaptureDeviceNV = NULL;
PFNWGLGETVIDEODEVICENVPROC wglGetVideoDeviceNV = NULL;
PFNWGLRELEASEVIDEODEVICENVPROC wglReleaseVideoDeviceNV = NULL;
PFNWGLBINDVIDEOIMAGENVPROC wglBindVideoImageNV = NULL;
PFNWGLRELEASEVIDEOIMAGENVPROC wglReleaseVideoImageNV = NULL;
PFNWGLSENDPBUFFERTOVIDEONVPROC wglSendPbufferToVideoNV = NULL;
PFNWGLGETVIDEOINFONVPROC wglGetVideoInfoNV = NULL;
PFNWGLGETSYNCVALUESOMLPROC wglGetSyncValuesOML = NULL;
PFNWGLGETMSCRATEOMLPROC wglGetMscRateOML = NULL;
PFNWGLSWAPBUFFERSMSCOMLPROC wglSwapBuffersMscOML = NULL;
PFNWGLSWAPLAYERBUFFERSMSCOMLPROC wglSwapLayerBuffersMscOML = NULL;
PFNWGLWAITFORMSCOMLPROC wglWaitForMscOML = NULL;
PFNWGLWAITFORSBCOMLPROC wglWaitForSbcOML = NULL;

#ifdef _WIN32

#ifdef _MSC_VER
#pragma warning(disable: 4055)
#pragma warning(disable: 4054)
#endif

static HMODULE g_module = NULL;

static int glgInitializeGlobals()
{
    // Load up the module:
    g_module = GetModuleHandleA("OpenGL32.dll");
    if (g_module == NULL)
        return 1;
    return 0;
}

static int glgTestPointer(const PROC pTest)
{
    ptrdiff_t iTest;
    // If pTest is NULL, then didn't find it.
    if (!pTest)
        return 0;
    // Test the pointer against common failure values.
    iTest = (ptrdiff_t)pTest;
    if (iTest == 1 || iTest == 2 || iTest == 3 || iTest == -1)
        return 0;
    // Not any of the previous? Return success.
    return 1;
}

static PROC glgGetProcAddress(const char* name)
{
    PROC pFunc = wglGetProcAddress((LPCSTR)name);
    if (glgTestPointer(pFunc))
        return pFunc;
    return (PROC)GetProcAddress(g_module, (LPCSTR)name);
}

#endif//_WIN32

// Loads the library.
static int glgLoadLibrary()
{
    int numFailed = 0;
	wglCreateBufferRegionARB = (PFNWGLCREATEBUFFERREGIONARBPROC)glgGetProcAddress("wglCreateBufferRegionARB");
	if (wglCreateBufferRegionARB == NULL) ++numFailed;
	wglDeleteBufferRegionARB = (PFNWGLDELETEBUFFERREGIONARBPROC)glgGetProcAddress("wglDeleteBufferRegionARB");
	if (wglDeleteBufferRegionARB == NULL) ++numFailed;
	wglSaveBufferRegionARB = (PFNWGLSAVEBUFFERREGIONARBPROC)glgGetProcAddress("wglSaveBufferRegionARB");
	if (wglSaveBufferRegionARB == NULL) ++numFailed;
	wglRestoreBufferRegionARB = (PFNWGLRESTOREBUFFERREGIONARBPROC)glgGetProcAddress("wglRestoreBufferRegionARB");
	if (wglRestoreBufferRegionARB == NULL) ++numFailed;
	wglCreateContextAttribsARB = (PFNWGLCREATECONTEXTATTRIBSARBPROC)glgGetProcAddress("wglCreateContextAttribsARB");
	if (wglCreateContextAttribsARB == NULL) ++numFailed;
	wglMakeContextCurrentARB = (PFNWGLMAKECONTEXTCURRENTARBPROC)glgGetProcAddress("wglMakeContextCurrentARB");
	if (wglMakeContextCurrentARB == NULL) ++numFailed;
	wglGetCurrentReadDCARB = (PFNWGLGETCURRENTREADDCARBPROC)glgGetProcAddress("wglGetCurrentReadDCARB");
	if (wglGetCurrentReadDCARB == NULL) ++numFailed;
	wglCreatePbufferARB = (PFNWGLCREATEPBUFFERARBPROC)glgGetProcAddress("wglCreatePbufferARB");
	if (wglCreatePbufferARB == NULL) ++numFailed;
	wglGetPbufferDCARB = (PFNWGLGETPBUFFERDCARBPROC)glgGetProcAddress("wglGetPbufferDCARB");
	if (wglGetPbufferDCARB == NULL) ++numFailed;
	wglReleasePbufferDCARB = (PFNWGLRELEASEPBUFFERDCARBPROC)glgGetProcAddress("wglReleasePbufferDCARB");
	if (wglReleasePbufferDCARB == NULL) ++numFailed;
	wglDestroyPbufferARB = (PFNWGLDESTROYPBUFFERARBPROC)glgGetProcAddress("wglDestroyPbufferARB");
	if (wglDestroyPbufferARB == NULL) ++numFailed;
	wglQueryPbufferARB = (PFNWGLQUERYPBUFFERARBPROC)glgGetProcAddress("wglQueryPbufferARB");
	if (wglQueryPbufferARB == NULL) ++numFailed;
	wglGetPixelFormatAttribivARB = (PFNWGLGETPIXELFORMATATTRIBIVARBPROC)glgGetProcAddress("wglGetPixelFormatAttribivARB");
	if (wglGetPixelFormatAttribivARB == NULL) ++numFailed;
	wglGetPixelFormatAttribfvARB = (PFNWGLGETPIXELFORMATATTRIBFVARBPROC)glgGetProcAddress("wglGetPixelFormatAttribfvARB");
	if (wglGetPixelFormatAttribfvARB == NULL) ++numFailed;
	wglChoosePixelFormatARB = (PFNWGLCHOOSEPIXELFORMATARBPROC)glgGetProcAddress("wglChoosePixelFormatARB");
	if (wglChoosePixelFormatARB == NULL) ++numFailed;
	wglBindTexImageARB = (PFNWGLBINDTEXIMAGEARBPROC)glgGetProcAddress("wglBindTexImageARB");
	if (wglBindTexImageARB == NULL) ++numFailed;
	wglReleaseTexImageARB = (PFNWGLRELEASETEXIMAGEARBPROC)glgGetProcAddress("wglReleaseTexImageARB");
	if (wglReleaseTexImageARB == NULL) ++numFailed;
	wglSetPbufferAttribARB = (PFNWGLSETPBUFFERATTRIBARBPROC)glgGetProcAddress("wglSetPbufferAttribARB");
	if (wglSetPbufferAttribARB == NULL) ++numFailed;
	wglSetStereoEmitterState3DL = (PFNWGLSETSTEREOEMITTERSTATE3DLPROC)glgGetProcAddress("wglSetStereoEmitterState3DL");
	if (wglSetStereoEmitterState3DL == NULL) ++numFailed;
	wglGetGPUIDsAMD = (PFNWGLGETGPUIDSAMDPROC)glgGetProcAddress("wglGetGPUIDsAMD");
	if (wglGetGPUIDsAMD == NULL) ++numFailed;
	wglGetGPUInfoAMD = (PFNWGLGETGPUINFOAMDPROC)glgGetProcAddress("wglGetGPUInfoAMD");
	if (wglGetGPUInfoAMD == NULL) ++numFailed;
	wglGetContextGPUIDAMD = (PFNWGLGETCONTEXTGPUIDAMDPROC)glgGetProcAddress("wglGetContextGPUIDAMD");
	if (wglGetContextGPUIDAMD == NULL) ++numFailed;
	wglCreateAssociatedContextAMD = (PFNWGLCREATEASSOCIATEDCONTEXTAMDPROC)glgGetProcAddress("wglCreateAssociatedContextAMD");
	if (wglCreateAssociatedContextAMD == NULL) ++numFailed;
	wglCreateAssociatedContextAttribsAMD = (PFNWGLCREATEASSOCIATEDCONTEXTATTRIBSAMDPROC)glgGetProcAddress("wglCreateAssociatedContextAttribsAMD");
	if (wglCreateAssociatedContextAttribsAMD == NULL) ++numFailed;
	wglDeleteAssociatedContextAMD = (PFNWGLDELETEASSOCIATEDCONTEXTAMDPROC)glgGetProcAddress("wglDeleteAssociatedContextAMD");
	if (wglDeleteAssociatedContextAMD == NULL) ++numFailed;
	wglMakeAssociatedContextCurrentAMD = (PFNWGLMAKEASSOCIATEDCONTEXTCURRENTAMDPROC)glgGetProcAddress("wglMakeAssociatedContextCurrentAMD");
	if (wglMakeAssociatedContextCurrentAMD == NULL) ++numFailed;
	wglGetCurrentAssociatedContextAMD = (PFNWGLGETCURRENTASSOCIATEDCONTEXTAMDPROC)glgGetProcAddress("wglGetCurrentAssociatedContextAMD");
	if (wglGetCurrentAssociatedContextAMD == NULL) ++numFailed;
	wglBlitContextFramebufferAMD = (PFNWGLBLITCONTEXTFRAMEBUFFERAMDPROC)glgGetProcAddress("wglBlitContextFramebufferAMD");
	if (wglBlitContextFramebufferAMD == NULL) ++numFailed;
	wglCreateDisplayColorTableEXT = (PFNWGLCREATEDISPLAYCOLORTABLEEXTPROC)glgGetProcAddress("wglCreateDisplayColorTableEXT");
	if (wglCreateDisplayColorTableEXT == NULL) ++numFailed;
	wglLoadDisplayColorTableEXT = (PFNWGLLOADDISPLAYCOLORTABLEEXTPROC)glgGetProcAddress("wglLoadDisplayColorTableEXT");
	if (wglLoadDisplayColorTableEXT == NULL) ++numFailed;
	wglBindDisplayColorTableEXT = (PFNWGLBINDDISPLAYCOLORTABLEEXTPROC)glgGetProcAddress("wglBindDisplayColorTableEXT");
	if (wglBindDisplayColorTableEXT == NULL) ++numFailed;
	wglDestroyDisplayColorTableEXT = (PFNWGLDESTROYDISPLAYCOLORTABLEEXTPROC)glgGetProcAddress("wglDestroyDisplayColorTableEXT");
	if (wglDestroyDisplayColorTableEXT == NULL) ++numFailed;
	wglMakeContextCurrentEXT = (PFNWGLMAKECONTEXTCURRENTEXTPROC)glgGetProcAddress("wglMakeContextCurrentEXT");
	if (wglMakeContextCurrentEXT == NULL) ++numFailed;
	wglGetCurrentReadDCEXT = (PFNWGLGETCURRENTREADDCEXTPROC)glgGetProcAddress("wglGetCurrentReadDCEXT");
	if (wglGetCurrentReadDCEXT == NULL) ++numFailed;
	wglCreatePbufferEXT = (PFNWGLCREATEPBUFFEREXTPROC)glgGetProcAddress("wglCreatePbufferEXT");
	if (wglCreatePbufferEXT == NULL) ++numFailed;
	wglGetPbufferDCEXT = (PFNWGLGETPBUFFERDCEXTPROC)glgGetProcAddress("wglGetPbufferDCEXT");
	if (wglGetPbufferDCEXT == NULL) ++numFailed;
	wglReleasePbufferDCEXT = (PFNWGLRELEASEPBUFFERDCEXTPROC)glgGetProcAddress("wglReleasePbufferDCEXT");
	if (wglReleasePbufferDCEXT == NULL) ++numFailed;
	wglDestroyPbufferEXT = (PFNWGLDESTROYPBUFFEREXTPROC)glgGetProcAddress("wglDestroyPbufferEXT");
	if (wglDestroyPbufferEXT == NULL) ++numFailed;
	wglQueryPbufferEXT = (PFNWGLQUERYPBUFFEREXTPROC)glgGetProcAddress("wglQueryPbufferEXT");
	if (wglQueryPbufferEXT == NULL) ++numFailed;
	wglGetPixelFormatAttribivEXT = (PFNWGLGETPIXELFORMATATTRIBIVEXTPROC)glgGetProcAddress("wglGetPixelFormatAttribivEXT");
	if (wglGetPixelFormatAttribivEXT == NULL) ++numFailed;
	wglGetPixelFormatAttribfvEXT = (PFNWGLGETPIXELFORMATATTRIBFVEXTPROC)glgGetProcAddress("wglGetPixelFormatAttribfvEXT");
	if (wglGetPixelFormatAttribfvEXT == NULL) ++numFailed;
	wglChoosePixelFormatEXT = (PFNWGLCHOOSEPIXELFORMATEXTPROC)glgGetProcAddress("wglChoosePixelFormatEXT");
	if (wglChoosePixelFormatEXT == NULL) ++numFailed;
	wglSwapIntervalEXT = (PFNWGLSWAPINTERVALEXTPROC)glgGetProcAddress("wglSwapIntervalEXT");
	if (wglSwapIntervalEXT == NULL) ++numFailed;
	wglGetSwapIntervalEXT = (PFNWGLGETSWAPINTERVALEXTPROC)glgGetProcAddress("wglGetSwapIntervalEXT");
	if (wglGetSwapIntervalEXT == NULL) ++numFailed;
	wglGetDigitalVideoParametersI3D = (PFNWGLGETDIGITALVIDEOPARAMETERSI3DPROC)glgGetProcAddress("wglGetDigitalVideoParametersI3D");
	if (wglGetDigitalVideoParametersI3D == NULL) ++numFailed;
	wglSetDigitalVideoParametersI3D = (PFNWGLSETDIGITALVIDEOPARAMETERSI3DPROC)glgGetProcAddress("wglSetDigitalVideoParametersI3D");
	if (wglSetDigitalVideoParametersI3D == NULL) ++numFailed;
	wglGetGammaTableParametersI3D = (PFNWGLGETGAMMATABLEPARAMETERSI3DPROC)glgGetProcAddress("wglGetGammaTableParametersI3D");
	if (wglGetGammaTableParametersI3D == NULL) ++numFailed;
	wglSetGammaTableParametersI3D = (PFNWGLSETGAMMATABLEPARAMETERSI3DPROC)glgGetProcAddress("wglSetGammaTableParametersI3D");
	if (wglSetGammaTableParametersI3D == NULL) ++numFailed;
	wglGetGammaTableI3D = (PFNWGLGETGAMMATABLEI3DPROC)glgGetProcAddress("wglGetGammaTableI3D");
	if (wglGetGammaTableI3D == NULL) ++numFailed;
	wglSetGammaTableI3D = (PFNWGLSETGAMMATABLEI3DPROC)glgGetProcAddress("wglSetGammaTableI3D");
	if (wglSetGammaTableI3D == NULL) ++numFailed;
	wglEnableGenlockI3D = (PFNWGLENABLEGENLOCKI3DPROC)glgGetProcAddress("wglEnableGenlockI3D");
	if (wglEnableGenlockI3D == NULL) ++numFailed;
	wglDisableGenlockI3D = (PFNWGLDISABLEGENLOCKI3DPROC)glgGetProcAddress("wglDisableGenlockI3D");
	if (wglDisableGenlockI3D == NULL) ++numFailed;
	wglIsEnabledGenlockI3D = (PFNWGLISENABLEDGENLOCKI3DPROC)glgGetProcAddress("wglIsEnabledGenlockI3D");
	if (wglIsEnabledGenlockI3D == NULL) ++numFailed;
	wglGenlockSourceI3D = (PFNWGLGENLOCKSOURCEI3DPROC)glgGetProcAddress("wglGenlockSourceI3D");
	if (wglGenlockSourceI3D == NULL) ++numFailed;
	wglGetGenlockSourceI3D = (PFNWGLGETGENLOCKSOURCEI3DPROC)glgGetProcAddress("wglGetGenlockSourceI3D");
	if (wglGetGenlockSourceI3D == NULL) ++numFailed;
	wglGenlockSourceEdgeI3D = (PFNWGLGENLOCKSOURCEEDGEI3DPROC)glgGetProcAddress("wglGenlockSourceEdgeI3D");
	if (wglGenlockSourceEdgeI3D == NULL) ++numFailed;
	wglGetGenlockSourceEdgeI3D = (PFNWGLGETGENLOCKSOURCEEDGEI3DPROC)glgGetProcAddress("wglGetGenlockSourceEdgeI3D");
	if (wglGetGenlockSourceEdgeI3D == NULL) ++numFailed;
	wglGenlockSampleRateI3D = (PFNWGLGENLOCKSAMPLERATEI3DPROC)glgGetProcAddress("wglGenlockSampleRateI3D");
	if (wglGenlockSampleRateI3D == NULL) ++numFailed;
	wglGetGenlockSampleRateI3D = (PFNWGLGETGENLOCKSAMPLERATEI3DPROC)glgGetProcAddress("wglGetGenlockSampleRateI3D");
	if (wglGetGenlockSampleRateI3D == NULL) ++numFailed;
	wglGenlockSourceDelayI3D = (PFNWGLGENLOCKSOURCEDELAYI3DPROC)glgGetProcAddress("wglGenlockSourceDelayI3D");
	if (wglGenlockSourceDelayI3D == NULL) ++numFailed;
	wglGetGenlockSourceDelayI3D = (PFNWGLGETGENLOCKSOURCEDELAYI3DPROC)glgGetProcAddress("wglGetGenlockSourceDelayI3D");
	if (wglGetGenlockSourceDelayI3D == NULL) ++numFailed;
	wglQueryGenlockMaxSourceDelayI3D = (PFNWGLQUERYGENLOCKMAXSOURCEDELAYI3DPROC)glgGetProcAddress("wglQueryGenlockMaxSourceDelayI3D");
	if (wglQueryGenlockMaxSourceDelayI3D == NULL) ++numFailed;
	wglCreateImageBufferI3D = (PFNWGLCREATEIMAGEBUFFERI3DPROC)glgGetProcAddress("wglCreateImageBufferI3D");
	if (wglCreateImageBufferI3D == NULL) ++numFailed;
	wglDestroyImageBufferI3D = (PFNWGLDESTROYIMAGEBUFFERI3DPROC)glgGetProcAddress("wglDestroyImageBufferI3D");
	if (wglDestroyImageBufferI3D == NULL) ++numFailed;
	wglAssociateImageBufferEventsI3D = (PFNWGLASSOCIATEIMAGEBUFFEREVENTSI3DPROC)glgGetProcAddress("wglAssociateImageBufferEventsI3D");
	if (wglAssociateImageBufferEventsI3D == NULL) ++numFailed;
	wglReleaseImageBufferEventsI3D = (PFNWGLRELEASEIMAGEBUFFEREVENTSI3DPROC)glgGetProcAddress("wglReleaseImageBufferEventsI3D");
	if (wglReleaseImageBufferEventsI3D == NULL) ++numFailed;
	wglEnableFrameLockI3D = (PFNWGLENABLEFRAMELOCKI3DPROC)glgGetProcAddress("wglEnableFrameLockI3D");
	if (wglEnableFrameLockI3D == NULL) ++numFailed;
	wglDisableFrameLockI3D = (PFNWGLDISABLEFRAMELOCKI3DPROC)glgGetProcAddress("wglDisableFrameLockI3D");
	if (wglDisableFrameLockI3D == NULL) ++numFailed;
	wglIsEnabledFrameLockI3D = (PFNWGLISENABLEDFRAMELOCKI3DPROC)glgGetProcAddress("wglIsEnabledFrameLockI3D");
	if (wglIsEnabledFrameLockI3D == NULL) ++numFailed;
	wglQueryFrameLockMasterI3D = (PFNWGLQUERYFRAMELOCKMASTERI3DPROC)glgGetProcAddress("wglQueryFrameLockMasterI3D");
	if (wglQueryFrameLockMasterI3D == NULL) ++numFailed;
	wglGetFrameUsageI3D = (PFNWGLGETFRAMEUSAGEI3DPROC)glgGetProcAddress("wglGetFrameUsageI3D");
	if (wglGetFrameUsageI3D == NULL) ++numFailed;
	wglBeginFrameTrackingI3D = (PFNWGLBEGINFRAMETRACKINGI3DPROC)glgGetProcAddress("wglBeginFrameTrackingI3D");
	if (wglBeginFrameTrackingI3D == NULL) ++numFailed;
	wglEndFrameTrackingI3D = (PFNWGLENDFRAMETRACKINGI3DPROC)glgGetProcAddress("wglEndFrameTrackingI3D");
	if (wglEndFrameTrackingI3D == NULL) ++numFailed;
	wglQueryFrameTrackingI3D = (PFNWGLQUERYFRAMETRACKINGI3DPROC)glgGetProcAddress("wglQueryFrameTrackingI3D");
	if (wglQueryFrameTrackingI3D == NULL) ++numFailed;
	wglDXSetResourceShareHandleNV = (PFNWGLDXSETRESOURCESHAREHANDLENVPROC)glgGetProcAddress("wglDXSetResourceShareHandleNV");
	if (wglDXSetResourceShareHandleNV == NULL) ++numFailed;
	wglDXOpenDeviceNV = (PFNWGLDXOPENDEVICENVPROC)glgGetProcAddress("wglDXOpenDeviceNV");
	if (wglDXOpenDeviceNV == NULL) ++numFailed;
	wglDXCloseDeviceNV = (PFNWGLDXCLOSEDEVICENVPROC)glgGetProcAddress("wglDXCloseDeviceNV");
	if (wglDXCloseDeviceNV == NULL) ++numFailed;
	wglDXRegisterObjectNV = (PFNWGLDXREGISTEROBJECTNVPROC)glgGetProcAddress("wglDXRegisterObjectNV");
	if (wglDXRegisterObjectNV == NULL) ++numFailed;
	wglDXUnregisterObjectNV = (PFNWGLDXUNREGISTEROBJECTNVPROC)glgGetProcAddress("wglDXUnregisterObjectNV");
	if (wglDXUnregisterObjectNV == NULL) ++numFailed;
	wglDXObjectAccessNV = (PFNWGLDXOBJECTACCESSNVPROC)glgGetProcAddress("wglDXObjectAccessNV");
	if (wglDXObjectAccessNV == NULL) ++numFailed;
	wglDXLockObjectsNV = (PFNWGLDXLOCKOBJECTSNVPROC)glgGetProcAddress("wglDXLockObjectsNV");
	if (wglDXLockObjectsNV == NULL) ++numFailed;
	wglDXUnlockObjectsNV = (PFNWGLDXUNLOCKOBJECTSNVPROC)glgGetProcAddress("wglDXUnlockObjectsNV");
	if (wglDXUnlockObjectsNV == NULL) ++numFailed;
	wglCopyImageSubDataNV = (PFNWGLCOPYIMAGESUBDATANVPROC)glgGetProcAddress("wglCopyImageSubDataNV");
	if (wglCopyImageSubDataNV == NULL) ++numFailed;
	wglDelayBeforeSwapNV = (PFNWGLDELAYBEFORESWAPNVPROC)glgGetProcAddress("wglDelayBeforeSwapNV");
	if (wglDelayBeforeSwapNV == NULL) ++numFailed;
	wglEnumGpusNV = (PFNWGLENUMGPUSNVPROC)glgGetProcAddress("wglEnumGpusNV");
	if (wglEnumGpusNV == NULL) ++numFailed;
	wglEnumGpuDevicesNV = (PFNWGLENUMGPUDEVICESNVPROC)glgGetProcAddress("wglEnumGpuDevicesNV");
	if (wglEnumGpuDevicesNV == NULL) ++numFailed;
	wglCreateAffinityDCNV = (PFNWGLCREATEAFFINITYDCNVPROC)glgGetProcAddress("wglCreateAffinityDCNV");
	if (wglCreateAffinityDCNV == NULL) ++numFailed;
	wglEnumGpusFromAffinityDCNV = (PFNWGLENUMGPUSFROMAFFINITYDCNVPROC)glgGetProcAddress("wglEnumGpusFromAffinityDCNV");
	if (wglEnumGpusFromAffinityDCNV == NULL) ++numFailed;
	wglDeleteDCNV = (PFNWGLDELETEDCNVPROC)glgGetProcAddress("wglDeleteDCNV");
	if (wglDeleteDCNV == NULL) ++numFailed;
	wglEnumerateVideoDevicesNV = (PFNWGLENUMERATEVIDEODEVICESNVPROC)glgGetProcAddress("wglEnumerateVideoDevicesNV");
	if (wglEnumerateVideoDevicesNV == NULL) ++numFailed;
	wglBindVideoDeviceNV = (PFNWGLBINDVIDEODEVICENVPROC)glgGetProcAddress("wglBindVideoDeviceNV");
	if (wglBindVideoDeviceNV == NULL) ++numFailed;
	wglQueryCurrentContextNV = (PFNWGLQUERYCURRENTCONTEXTNVPROC)glgGetProcAddress("wglQueryCurrentContextNV");
	if (wglQueryCurrentContextNV == NULL) ++numFailed;
	wglJoinSwapGroupNV = (PFNWGLJOINSWAPGROUPNVPROC)glgGetProcAddress("wglJoinSwapGroupNV");
	if (wglJoinSwapGroupNV == NULL) ++numFailed;
	wglBindSwapBarrierNV = (PFNWGLBINDSWAPBARRIERNVPROC)glgGetProcAddress("wglBindSwapBarrierNV");
	if (wglBindSwapBarrierNV == NULL) ++numFailed;
	wglQuerySwapGroupNV = (PFNWGLQUERYSWAPGROUPNVPROC)glgGetProcAddress("wglQuerySwapGroupNV");
	if (wglQuerySwapGroupNV == NULL) ++numFailed;
	wglQueryMaxSwapGroupsNV = (PFNWGLQUERYMAXSWAPGROUPSNVPROC)glgGetProcAddress("wglQueryMaxSwapGroupsNV");
	if (wglQueryMaxSwapGroupsNV == NULL) ++numFailed;
	wglQueryFrameCountNV = (PFNWGLQUERYFRAMECOUNTNVPROC)glgGetProcAddress("wglQueryFrameCountNV");
	if (wglQueryFrameCountNV == NULL) ++numFailed;
	wglResetFrameCountNV = (PFNWGLRESETFRAMECOUNTNVPROC)glgGetProcAddress("wglResetFrameCountNV");
	if (wglResetFrameCountNV == NULL) ++numFailed;
	wglFreeMemoryNV = (PFNWGLFREEMEMORYNVPROC)glgGetProcAddress("wglFreeMemoryNV");
	if (wglFreeMemoryNV == NULL) ++numFailed;
	wglBindVideoCaptureDeviceNV = (PFNWGLBINDVIDEOCAPTUREDEVICENVPROC)glgGetProcAddress("wglBindVideoCaptureDeviceNV");
	if (wglBindVideoCaptureDeviceNV == NULL) ++numFailed;
	wglEnumerateVideoCaptureDevicesNV = (PFNWGLENUMERATEVIDEOCAPTUREDEVICESNVPROC)glgGetProcAddress("wglEnumerateVideoCaptureDevicesNV");
	if (wglEnumerateVideoCaptureDevicesNV == NULL) ++numFailed;
	wglLockVideoCaptureDeviceNV = (PFNWGLLOCKVIDEOCAPTUREDEVICENVPROC)glgGetProcAddress("wglLockVideoCaptureDeviceNV");
	if (wglLockVideoCaptureDeviceNV == NULL) ++numFailed;
	wglQueryVideoCaptureDeviceNV = (PFNWGLQUERYVIDEOCAPTUREDEVICENVPROC)glgGetProcAddress("wglQueryVideoCaptureDeviceNV");
	if (wglQueryVideoCaptureDeviceNV == NULL) ++numFailed;
	wglReleaseVideoCaptureDeviceNV = (PFNWGLRELEASEVIDEOCAPTUREDEVICENVPROC)glgGetProcAddress("wglReleaseVideoCaptureDeviceNV");
	if (wglReleaseVideoCaptureDeviceNV == NULL) ++numFailed;
	wglGetVideoDeviceNV = (PFNWGLGETVIDEODEVICENVPROC)glgGetProcAddress("wglGetVideoDeviceNV");
	if (wglGetVideoDeviceNV == NULL) ++numFailed;
	wglReleaseVideoDeviceNV = (PFNWGLRELEASEVIDEODEVICENVPROC)glgGetProcAddress("wglReleaseVideoDeviceNV");
	if (wglReleaseVideoDeviceNV == NULL) ++numFailed;
	wglBindVideoImageNV = (PFNWGLBINDVIDEOIMAGENVPROC)glgGetProcAddress("wglBindVideoImageNV");
	if (wglBindVideoImageNV == NULL) ++numFailed;
	wglReleaseVideoImageNV = (PFNWGLRELEASEVIDEOIMAGENVPROC)glgGetProcAddress("wglReleaseVideoImageNV");
	if (wglReleaseVideoImageNV == NULL) ++numFailed;
	wglSendPbufferToVideoNV = (PFNWGLSENDPBUFFERTOVIDEONVPROC)glgGetProcAddress("wglSendPbufferToVideoNV");
	if (wglSendPbufferToVideoNV == NULL) ++numFailed;
	wglGetVideoInfoNV = (PFNWGLGETVIDEOINFONVPROC)glgGetProcAddress("wglGetVideoInfoNV");
	if (wglGetVideoInfoNV == NULL) ++numFailed;
	wglGetSyncValuesOML = (PFNWGLGETSYNCVALUESOMLPROC)glgGetProcAddress("wglGetSyncValuesOML");
	if (wglGetSyncValuesOML == NULL) ++numFailed;
	wglGetMscRateOML = (PFNWGLGETMSCRATEOMLPROC)glgGetProcAddress("wglGetMscRateOML");
	if (wglGetMscRateOML == NULL) ++numFailed;
	wglSwapBuffersMscOML = (PFNWGLSWAPBUFFERSMSCOMLPROC)glgGetProcAddress("wglSwapBuffersMscOML");
	if (wglSwapBuffersMscOML == NULL) ++numFailed;
	wglSwapLayerBuffersMscOML = (PFNWGLSWAPLAYERBUFFERSMSCOMLPROC)glgGetProcAddress("wglSwapLayerBuffersMscOML");
	if (wglSwapLayerBuffersMscOML == NULL) ++numFailed;
	wglWaitForMscOML = (PFNWGLWAITFORMSCOMLPROC)glgGetProcAddress("wglWaitForMscOML");
	if (wglWaitForMscOML == NULL) ++numFailed;
	wglWaitForSbcOML = (PFNWGLWAITFORSBCOMLPROC)glgGetProcAddress("wglWaitForSbcOML");
	if (wglWaitForSbcOML == NULL) ++numFailed;
    return numFailed;
} //glgLoadLibrary

static const char * (WINAPI *wglGetExtensionsStringARB)(HDC) = NULL;

int wglgLoadFunctions()
{
    int numFailed = 0;
    int failed = 0;

    // Init the globals needed
    if (glgInitializeGlobals())
        return -1;

    // Pull GetExtensionsString for extension loading.
    wglGetExtensionsStringARB = (const char * (WINAPI *)(HDC))glgGetProcAddress("wglGetExtensionsStringARB");
    if (!wglGetExtensionsStringARB) {
        ++numFailed;
        failed = 1;
    }

    // Now, load the actual library.
    if (!failed) 
        numFailed += glgLoadLibrary();

    // We made it!
    if (failed == 0)
        return numFailed;
    else 
        return -numFailed;
}
#ifdef __cplusplus
} /*extern "C"*/
#endif /*__cplusplus*/
#endif /*_WIN32*/
