
#ifndef _TERRAIN_BIOME_TYPES_H_
#define _TERRAIN_BIOME_TYPES_H_

#include "core/types/types.h"

namespace Terrain
{
	enum EBiomeType : uint8_t
	{
		BIO_DEFAULT = 0,
		BIO_TUNDRA		= 1,	BIO_TAIGA		= 1|128,
		BIO_SAVANNA		= 2,	BIO_EVERGREEN	= 2|128,
		BIO_GRASSLAND	= 3,	BIO_TEMPERATE	= 3|128,
		BIO_TROPICAL	= 4,	BIO_RAINFOREST	= 4|128,
		BIO_MOIST		= 5,	BIO_SWAMP		= 5|128,

		BIO_S_TUNDRA,
		BIO_DESERT,			BIO_COLD_DESERT,		BIO_GRASS_DESERT,
		BIO_OUTLANDS,		BIO_WET_OUTLANDS,
		BIO_THE_EDGE,

		SUB_BIO_ASHLANDS,			SUB_BIO_SMALLLANDS,

		BIO_MAX_COUNT
	};
}

#endif//_TERRAIN_BIOME_TYPES_H_