/*
 *
 * Confidential Information of Telekinesys Research Limited (t/a Havok). Not for disclosure or distribution without Havok's
 * prior written consent. This software contains code, techniques and know-how which is confidential and proprietary to Havok.
 * Level 2 and Level 3 source code contains trade secrets of Havok. Havok Software (C) Copyright 1999-2012 Telekinesys Research Limited t/a Havok. All Rights Reserved. Use of this software is subject to the terms of an end user license agreement.
 *
 */

//HK_REFLECTION_PARSER_EXCLUDE_FILE

// Autogenerated by generateReflections.py (projectClassList.py)
// Changes will not be lost unless:
// - The workspace is re-generated using build.py
// - The corresponding reflection database (reflection.db) is deleted
// - The --force-output or --force-rebuild option is added to the pre-build generateReflection.py execution

#include "Reflections/hkRefCountedPropertiesReflection.cpp"
#include "Reflections/hkQTransformReflection.cpp"
#include "Reflections/hkCustomAttributesReflection.cpp"
#include "Reflections/hkSphereReflection.cpp"
#include "Reflections/hkSetReflection.cpp"
#include "Reflections/hkLocalFrameReflection.cpp"
#include "Reflections/hkClassMemberReflection.cpp"
#include "Reflections/hkTraceStreamReflection.cpp"
#include "Reflections/hkSweptTransformReflection.cpp"
#include "Reflections/hkAabbReflection.cpp"
#include "Reflections/hkMotionStateReflection.cpp"
#include "Reflections/hkAttributesReflection.cpp"
#include "Reflections/hkPackedVector3Reflection.cpp"
#include "Reflections/hkValueTypeFreeListReflection.cpp"
#include "Reflections/hkContactPointMaterialReflection.cpp"
#include "Reflections/hkContactPointReflection.cpp"
#include "Reflections/hkClassEnumReflection.cpp"
#include "Reflections/hkGeometryReflection.cpp"
#include "Reflections/hkBitFieldReflection.cpp"
#include "Reflections/hkAabbHalfReflection.cpp"
#include "Reflections/hkFloat16TransformReflection.cpp"
#include "Reflections/hkFourTransposedPointsReflection.cpp"
#include "Reflections/hkBaseTypesReflection.cpp"
#include "Reflections/hkClassReflection.cpp"
#include "Reflections/hkMultiThreadCheckReflection.cpp"
#include "Reflections/hkColorReflection.cpp"
#ifndef HK_EXCLUDE_FEATURE_BaseObject
#include "Reflections/BaseObjecthkBaseObjectReflection.cpp"
#include "Reflections/BaseObjecthkReferencedObjectReflection.cpp"
#endif
#ifndef HK_EXCLUDE_FEATURE_hkMonitorStream
#include "Reflections/hkMonitorStreamhkMonitorStreamAnalyzerReflection.cpp"
#endif

/*
 * Havok SDK - NO SOURCE PC DOWNLOAD, BUILD(#20120119)
 * 
 * Confidential Information of Havok.  (C) Copyright 1999-2012
 * Telekinesys Research Limited t/a Havok. All Rights Reserved. The Havok
 * Logo, and the Havok buzzsaw logo are trademarks of Havok.  Title, ownership
 * rights, and intellectual property rights in the Havok software remain in
 * Havok and/or its suppliers.
 * 
 * Use of this software for evaluation purposes is subject to and indicates
 * acceptance of the End User licence Agreement for this product. A copy of
 * the license is included with this software and is also available at www.havok.com/tryhavok.
 * 
 */
