/*
 *
 * Confidential Information of Telekinesys Research Limited (t/a Havok). Not for disclosure or distribution without Havok's
 * prior written consent. This software contains code, techniques and know-how which is confidential and proprietary to Havok.
 * Level 2 and Level 3 source code contains trade secrets of Havok. Havok Software (C) Copyright 1999-2012 Telekinesys Research Limited t/a Havok. All Rights Reserved. Use of this software is subject to the terms of an end user license agreement.
 *
 */

//HK_REFLECTION_PARSER_EXCLUDE_FILE

// Autogenerated by generateReflections.py (projectClassList.py)
// Changes will not be lost unless:
// - The workspace is re-generated using build.py
// - The corresponding reflection database (reflection.db) is deleted
// - The --force-output or --force-rebuild option is added to the pre-build generateReflection.py execution

HK_ABSTRACT_CLASS(hkLocalFrame)
HK_CLASS(hkLocalFrameGroup)
HK_CLASS(hkRefCountedProperties)
HK_CLASS(hkSimpleLocalFrame)
HK_STRUCT(hkAabb)
HK_STRUCT(hkAabbHalf)
HK_STRUCT(hkAabbUint32)
HK_STRUCT(hkArrayTypeAttribute)
HK_STRUCT(hkBitField)
HK_STRUCT(hkClass)
HK_STRUCT(hkClassEnum)
HK_STRUCT(hkClassEnumItem)
HK_STRUCT(hkClassMember)
HK_STRUCT(hkColor)
HK_STRUCT(hkContactPoint)
HK_STRUCT(hkContactPointMaterial)
HK_STRUCT(hkCustomAttributes)
HK_STRUCT(hkCustomAttributesAttribute)
HK_STRUCT(hkDataObjectTypeAttribute)
HK_STRUCT(hkDescriptionAttribute)
HK_STRUCT(hkDocumentationAttribute)
HK_STRUCT(hkFloat16)
HK_STRUCT(hkFloat16Transform)
HK_STRUCT(hkFourTransposedPoints)
HK_STRUCT(hkGeometry)
HK_STRUCT(hkGeometryTriangle)
HK_STRUCT(hkGizmoAttribute)
HK_STRUCT(hkLinkAttribute)
HK_STRUCT(hkModelerNodeTypeAttribute)
HK_STRUCT(hkMotionState)
HK_STRUCT(hkMultiThreadCheck)
HK_STRUCT(hkPackedVector3)
HK_STRUCT(hkPostFinishAttribute)
HK_STRUCT(hkQTransform)
HK_STRUCT(hkRangeInt32Attribute)
HK_STRUCT(hkRangeRealAttribute)
HK_STRUCT(hkRefCountedPropertiesEntry)
HK_STRUCT(hkSemanticsAttribute)
HK_STRUCT(hkSetUint32)
HK_STRUCT(hkSetunsignedinthkContainerHeapAllocatorhkMapOperationsunsignedint)
HK_STRUCT(hkSphere)
HK_STRUCT(hkSweptTransform)
HK_STRUCT(hkTraceStreamTitle)
HK_STRUCT(hkUiAttribute)
#ifndef HK_EXCLUDE_FEATURE_BaseObject
HK_CLASS(hkBaseObject)
HK_CLASS(hkReferencedObject)
#endif
#ifndef HK_EXCLUDE_FEATURE_hkMonitorStream
HK_CLASS(hkMonitorStreamColorTable)
HK_STRUCT(hkMonitorStreamColorTableColorPair)
HK_STRUCT(hkMonitorStreamFrameInfo)
HK_STRUCT(hkMonitorStreamStringMap)
HK_STRUCT(hkMonitorStreamStringMapStringMap)
#endif

/*
 * Havok SDK - NO SOURCE PC DOWNLOAD, BUILD(#20120119)
 * 
 * Confidential Information of Havok.  (C) Copyright 1999-2012
 * Telekinesys Research Limited t/a Havok. All Rights Reserved. The Havok
 * Logo, and the Havok buzzsaw logo are trademarks of Havok.  Title, ownership
 * rights, and intellectual property rights in the Havok software remain in
 * Havok and/or its suppliers.
 * 
 * Use of this software for evaluation purposes is subject to and indicates
 * acceptance of the End User licence Agreement for this product. A copy of
 * the license is included with this software and is also available at www.havok.com/tryhavok.
 * 
 */
