#ifndef TOOL_SHELL_THUMBNAIL_BPD_PROVIDER_H_
#define TOOL_SHELL_THUMBNAIL_BPD_PROVIDER_H_

HRESULT CBpdThumbnailProvider_CreateInstance( REFIID riid, void **ppv );

#endif//TOOL_SHELL_THUMBNAIL_BPD_PROVIDER_H_