
#ifndef _TERRAIN_WEATHER_TYPES_H_
#define _TERRAIN_WEATHER_TYPES_H_

#include "core/types/types.h"

namespace Terrain
{
	enum EWeatherType : uint8_t
	{
		WTH_NONE = 0,
		WTH_LIGHT_RAIN,
		WTH_HEAVY_RAIN,
		WTH_LIGHT_RAIN_THUNDER,
		WTH_HEAVY_RAIN_THUNDER,
		WTH_LIGHT_SNOW,
		WTH_HEAVY_SNOW,
		WTH_STORM_SNOW,
		WTH_DUST_STORM,
		WTH_FIRE_AND_BRIMSTONE,
		WTH_ICE_STORM,
		WTH_FLUXX_STORM,
		WTH_FOG_LIGHT
	};
}

#endif//_TERRAIN_WEATHER_TYPES_H_