
#ifndef _ENGINE_COMMON_PARTICLE_ENUMERATIONS_H_
#define _ENGINE_COMMON_PARTICLE_ENUMERATIONS_H_

#include "core/types.h"

namespace Engine
{
	enum ParticleSystemComponent_t : uint32_t
	{
		PARTICLESYS_EMITTER		= 0,
		PARTICLESYS_UPDATER		= 1,
		PARTICLESYS_RENDERER	= 2,

		PARTICLESYS_EMITTER_CLOUDS		= 3,
		PARTICLESYS_RENDERER_ANIMATED	= 5,

		PARTICLESYS_MODIFIER_WIND		= 4,
		PARTICLESYS_MODIFIER_SPIRAL		= 6,
	};
}

#endif//_ENGINE_COMMON_PARTICLE_ENUMERATIONS_H_